#!/bin/bash
#
# Run all dotfiles installers.

set -e

SCRIPT_ROOT="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
cd "$SCRIPT_ROOT/.."

# Find the installers and run them iteratively
find . -name install.sh | xargs -I{} /bin/bash {}
