alias jmi="jira_my_issues"
alias jmai="jira_my_active_issues"
alias jst="jira_start_issue"
alias jd="jira_complete_current_issue"
alias jmvc="jira_move_current_issue"
alias jci="jira_current_issue"
alias jiv="jira issue view"
